server:
  port: 8886
spring:
  application:
    name: eureka-service
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://peer1:8887/eureka/