eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8887/eureka/,http://peer2:8886/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      sensitiveHeaders: Authorization
      path: /api-user/**
      service-id: user-service
    api-b:
      sensitiveHeaders: Authorization
      path: /api-order/**
      service-id: order-service
    api-c:
      sensitiveHeaders: Authorization
      path: /api-fegin-order/**
      service-id: service-order-feign
    api-d:
      sensitiveHeaders: Authorization
      path: /api-security/**
      service-id: security-service
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    #MaxAutoRetries: 1
    #MaxAutoRetriesNextServer: 2
    