eureka:
  client:
    service-url:
      defaultZone: http://localhost:8887/eureka/
server:
  port: '7010'
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        default-application-name: config-server
        git:
          password: ''
          search-paths: myconfigpath
          uri: https://gitee.com/toorui/springcloud-config.git
          username: ''
dnv:
  test
