server:
  port: 8766
spring:
  application:
    name: winsun-fegin-service
feign:
   hystrix:
     enabled: true
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE
#          timeoutInMilliseconds: 5000
hystrix:
   command: 
     default: 
       execution: 
        isolation:
         thread: 
          timeoutInMilliseconds: 5000
winsum:
  admin:
    serviceId: winsun-service
