server:
  port: 8887
spring:
  application:
    name: eureka-service
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://peer2:8886/eureka/